# Generated by Django 3.0.4 on 2020-07-18 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductList',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('productName', models.CharField(max_length=50, verbose_name='名称')),
                ('version', models.IntegerField(verbose_name='版本号')),
                ('productType', models.CharField(choices=[('Web', 'Web'), ('App', 'App')], max_length=30, verbose_name='项目类型')),
                ('desc', models.CharField(blank=True, max_length=10000, null=True, verbose_name='备注')),
                ('createTime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('lastUpdateTime', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
        ),
        migrations.CreateModel(
            name='Usr',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('user_name', models.CharField(max_length=50, verbose_name='用戶名称')),
                ('user_id', models.CharField(max_length=50, verbose_name='账号')),
                ('user_status', models.CharField(max_length=2, verbose_name='状态')),
            ],
            options={
                'ordering': ('-create_time',),
            },
        ),
        migrations.CreateModel(
            name='ApiInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='接口名称')),
                ('httpType', models.CharField(choices=[('HTTPS', 'HTTPS'), ('HTTP', 'HTTP')], max_length=50, verbose_name='协议类型')),
                ('requestType', models.CharField(choices=[('GET', 'get'), ('POST', 'get'), ('PUT', 'put'), ('DELETE', 'delete')], max_length=50, verbose_name='请求方式')),
                ('header', models.CharField(max_length=1024, verbose_name='请求头')),
                ('apiUrl', models.CharField(max_length=1024, verbose_name='接口地址')),
                ('requestParameterType', models.CharField(choices=[('raw', 'raw'), ('form-data', 'form-data')], max_length=30, verbose_name='参数类型')),
                ('requestParameter', models.CharField(max_length=1024, verbose_name='请求参数')),
                ('response', models.CharField(max_length=1024, verbose_name='响应内容')),
                ('status', models.BooleanField(default=True, verbose_name='状态')),
                ('productId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spo.ProductList', verbose_name='所属项目')),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
    ]
