# Generated by Django 3.0.4 on 2020-08-03 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApiInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='接口名称')),
                ('httpType', models.CharField(choices=[('HTTPS', 'https'), ('HTTP', 'http')], max_length=50, verbose_name='协议类型')),
                ('requestType', models.CharField(choices=[('GET', 'get'), ('POST', 'post'), ('PUT', 'put'), ('DELETE', 'delete')], max_length=50, verbose_name='请求方式')),
                ('apiUrl', models.CharField(max_length=1024, verbose_name='接口地址')),
                ('requestParameterType', models.CharField(choices=[('raw', 'raw'), ('form-data', 'form-data')], max_length=30, verbose_name='参数类型')),
                ('status', models.BooleanField(default=True, verbose_name='状态')),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='ProjectList',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('projectName', models.CharField(max_length=50, verbose_name='名称')),
                ('version', models.IntegerField(verbose_name='版本号')),
                ('projectType', models.CharField(choices=[('Web', 'Web'), ('App', 'App')], max_length=30, verbose_name='项目类型')),
                ('desc', models.CharField(blank=True, max_length=1024, null=True, verbose_name='备注')),
                ('status', models.BooleanField(default=False, verbose_name='状态')),
                ('createTime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updateTime', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('taskName', models.CharField(max_length=50, verbose_name='任务名称')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_proj', to='spo.ProjectList', verbose_name='所属项目')),
            ],
        ),
        migrations.CreateModel(
            name='TestResult',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('res_content', models.CharField(max_length=50, verbose_name='响应内容')),
                ('testResult', models.CharField(max_length=50, verbose_name='测试结果')),
                ('updateTime', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('api', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='api_result', to='spo.ApiInfo', verbose_name='接口')),
            ],
        ),
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('caseName', models.CharField(max_length=50, verbose_name='用例名称')),
                ('description', models.CharField(blank=True, max_length=1024, null=True, verbose_name='描述')),
                ('updateTime', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='case_proj', to='spo.ProjectList', verbose_name='所属项目')),
                ('task', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='case_task', to='spo.Task', verbose_name='所属任务')),
            ],
        ),
        migrations.CreateModel(
            name='ApiResponse',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('res_type', models.CharField(choices=[('Int', 'Int'), ('String', 'String')], default='String', max_length=1024, verbose_name='参数类型')),
                ('res_key', models.CharField(max_length=1024, verbose_name='名称')),
                ('res_value', models.CharField(max_length=1024, verbose_name='值')),
                ('description', models.CharField(blank=True, max_length=1024, null=True, verbose_name='描述')),
                ('api', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_resp', to='spo.ApiInfo', verbose_name='所属接口')),
            ],
        ),
        migrations.CreateModel(
            name='ApiParRaw',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('raw_data', models.TextField(blank=True, null=True, verbose_name='内容')),
                ('api', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_parraw', to='spo.ApiInfo', verbose_name='所属接口')),
            ],
            options={
                'verbose_name': '请求类型Raw',
            },
        ),
        migrations.CreateModel(
            name='ApiParameter',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('par_key', models.CharField(max_length=1024, verbose_name='名称')),
                ('par_value', models.CharField(max_length=1024, verbose_name='值')),
                ('par_type', models.CharField(choices=[('Int', 'Int'), ('String', 'String')], default='String', max_length=1024, verbose_name='参数类型')),
                ('required', models.BooleanField(default=True, verbose_name='是否必填')),
                ('description', models.CharField(blank=True, max_length=1024, null=True, verbose_name='描述')),
                ('api', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_parameter', to='spo.ApiInfo', verbose_name='所属接口')),
            ],
            options={
                'verbose_name': '请求参数',
            },
        ),
        migrations.AddField(
            model_name='apiinfo',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_proj', to='spo.ProjectList', verbose_name='所属项目'),
        ),
        migrations.CreateModel(
            name='ApiHeaders',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('head_key', models.CharField(max_length=1024, verbose_name='名称')),
                ('head_value', models.CharField(max_length=1024, verbose_name='值')),
                ('api', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_header', to='spo.ApiInfo', verbose_name='所属接口')),
            ],
            options={
                'verbose_name': '请求头',
            },
        ),
    ]
