# Generated by Django 3.0.8 on 2020-07-12 22:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apiinfo',
            name='baseUrl',
        ),
        migrations.AddField(
            model_name='apiinfo',
            name='header',
            field=models.CharField(default='', max_length=1024, verbose_name='请求头'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='apiinfo',
            name='productId',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='spo.ProductList', verbose_name='所属项目'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='apiinfo',
            name='response',
            field=models.CharField(default='', max_length=1024, verbose_name='响应内容'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='apiinfo',
            name='status',
            field=models.BooleanField(default=True, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='apiinfo',
            name='httpType',
            field=models.CharField(choices=[('HTTPS', 'HTTPS'), ('HTTP', 'HTTP')], max_length=50, verbose_name='协议类型'),
        ),
        migrations.AlterField(
            model_name='apiinfo',
            name='requestType',
            field=models.CharField(choices=[('GET', 'get'), ('POST', 'get'), ('PUT', 'put'), ('DELETE', 'delete')], max_length=50, verbose_name='请求方式'),
        ),
        migrations.AlterField(
            model_name='productlist',
            name='version',
            field=models.IntegerField(verbose_name='版本号'),
        ),
    ]
