# Generated by Django 3.0.4 on 2020-07-18 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usr',
            name='password',
            field=models.CharField(default='', max_length=100, verbose_name='密码'),
            preserve_default=False,
        ),
    ]
