# Generated by Django 3.0.4 on 2020-08-04 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apiparraw',
            name='api',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='api_parraw', to='spo.ApiInfo', verbose_name='所属接口'),
        ),
    ]
