# Generated by Django 3.0.4 on 2020-06-19 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spo', '0002_auto_20200612_1545'),
    ]

    operations = [
        migrations.AddField(
            model_name='apiinfo',
            name='productId',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='spo.ProductList', verbose_name='所属项目'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='apiinfo',
            name='status',
            field=models.BooleanField(default=True, verbose_name='状态'),
        ),
    ]
